<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MicroBlogLikeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //'user_id',
        // 'micro_blog_id',
        DB::table('micro_blog_favourites');
        $micro_blog_favourites = [
            ['user_id' => 1, 'micro_blog_id' => 1],
            ['user_id' => 1, 'micro_blog_id' => 2],
            ['user_id' => 1, 'micro_blog_id' => 4],
            ['user_id' => 2, 'micro_blog_id' => 1],
            ['user_id' => 2, 'micro_blog_id' => 4],
            ['user_id' => 2, 'micro_blog_id' => 5],
            ['user_id' => 2, 'micro_blog_id' => 6],
            ['user_id' => 3, 'micro_blog_id' => 2],
            ['user_id' => 3, 'micro_blog_id' => 3],
            ['user_id' => 3, 'micro_blog_id' => 5],
            ['user_id' => 3, 'micro_blog_id' => 6],
            ['user_id' => 4, 'micro_blog_id' => 1],
            ['user_id' => 4, 'micro_blog_id' => 2],
            ['user_id' => 4, 'micro_blog_id' => 4],
            ['user_id' => 4, 'micro_blog_id' => 5],
            ['user_id' => 4, 'micro_blog_id' => 6],
            ['user_id' => 5, 'micro_blog_id' => 1],
            ['user_id' => 5, 'micro_blog_id' => 2],
            ['user_id' => 5, 'micro_blog_id' => 3],
            ['user_id' => 5, 'micro_blog_id' => 4],
            ['user_id' => 5, 'micro_blog_id' => 5],
            ['user_id' => 5, 'micro_blog_id' => 6],
            ['user_id' => 6, 'micro_blog_id' => 1],
            ['user_id' => 6, 'micro_blog_id' => 3],
            ['user_id' => 6, 'micro_blog_id' => 4],
            ['user_id' => 6, 'micro_blog_id' => 5],
            ['user_id' => 7, 'micro_blog_id' => 1],
            ['user_id' => 7, 'micro_blog_id' => 2],
            ['user_id' => 7, 'micro_blog_id' => 3],
            ['user_id' => 7, 'micro_blog_id' => 5],
            ['user_id' => 8, 'micro_blog_id' => 1],
            ['user_id' => 8, 'micro_blog_id' => 2],
            ['user_id' => 8, 'micro_blog_id' => 3],
            ['user_id' => 8, 'micro_blog_id' => 4],
            ['user_id' => 8, 'micro_blog_id' => 5],
            ['user_id' => 8, 'micro_blog_id' => 6],
            ['user_id' => 9, 'micro_blog_id' => 1],
            ['user_id' => 9, 'micro_blog_id' => 2],
            ['user_id' => 9, 'micro_blog_id' => 3],
            ['user_id' => 9, 'micro_blog_id' => 4],
            ['user_id' => 9, 'micro_blog_id' => 5],
            ['user_id' => 9, 'micro_blog_id' => 6],
            ['user_id' => 10, 'micro_blog_id' => 1],
            ['user_id' => 10, 'micro_blog_id' => 2],
            ['user_id' => 10, 'micro_blog_id' => 4],
            ['user_id' => 10, 'micro_blog_id' => 5],
            ['user_id' => 10, 'micro_blog_id' => 6],
            ['user_id' => 11, 'micro_blog_id' => 1],
            ['user_id' => 11, 'micro_blog_id' => 2],
            ['user_id' => 11, 'micro_blog_id' => 3],
            ['user_id' => 11, 'micro_blog_id' => 4],
            ['user_id' => 11, 'micro_blog_id' => 5],
            ['user_id' => 11, 'micro_blog_id' => 6],
            ['user_id' => 12, 'micro_blog_id' => 2],
            ['user_id' => 12, 'micro_blog_id' => 4],
            ['user_id' => 12, 'micro_blog_id' => 6],
            ['user_id' => 13, 'micro_blog_id' => 1],
            ['user_id' => 13, 'micro_blog_id' => 2],
            ['user_id' => 13, 'micro_blog_id' => 3],
            ['user_id' => 13, 'micro_blog_id' => 4],
            ['user_id' => 13, 'micro_blog_id' => 5],
            ['user_id' => 13, 'micro_blog_id' => 6],
            ['user_id' => 14, 'micro_blog_id' => 1],
            ['user_id' => 14, 'micro_blog_id' => 2],
            ['user_id' => 14, 'micro_blog_id' => 3],
            ['user_id' => 14, 'micro_blog_id' => 4],
            ['user_id' => 14, 'micro_blog_id' => 5],
            ['user_id' => 14, 'micro_blog_id' => 6],
            ['user_id' => 15, 'micro_blog_id' => 1],
            ['user_id' => 15, 'micro_blog_id' => 2],
            ['user_id' => 15, 'micro_blog_id' => 3],
            ['user_id' => 15, 'micro_blog_id' => 4],
            ['user_id' => 15, 'micro_blog_id' => 6],
            ['user_id' => 16, 'micro_blog_id' => 1],
            ['user_id' => 16, 'micro_blog_id' => 2],
            ['user_id' => 16, 'micro_blog_id' => 3],
            ['user_id' => 16, 'micro_blog_id' => 4],
            ['user_id' => 16, 'micro_blog_id' => 5],
            ['user_id' => 17, 'micro_blog_id' => 1],
            ['user_id' => 17, 'micro_blog_id' => 2],
            ['user_id' => 17, 'micro_blog_id' => 3],
            ['user_id' => 17, 'micro_blog_id' => 4],
            ['user_id' => 17, 'micro_blog_id' => 5],
            ['user_id' => 17, 'micro_blog_id' => 6],
            ['user_id' => 18, 'micro_blog_id' => 1],
            ['user_id' => 18, 'micro_blog_id' => 2],
            ['user_id' => 18, 'micro_blog_id' => 4],
            ['user_id' => 18, 'micro_blog_id' => 5],
            ['user_id' => 18, 'micro_blog_id' => 6],
            ['user_id' => 19, 'micro_blog_id' => 1],
            ['user_id' => 19, 'micro_blog_id' => 2],
            ['user_id' => 19, 'micro_blog_id' => 3],
            ['user_id' => 19, 'micro_blog_id' => 4],
            ['user_id' => 19, 'micro_blog_id' => 5],
            ['user_id' => 19, 'micro_blog_id' => 6],
            ['user_id' => 20, 'micro_blog_id' => 1],
            ['user_id' => 20, 'micro_blog_id' => 3],
            ['user_id' => 20, 'micro_blog_id' => 4],        
        ];
        DB::table('micro_blog_favourites')->insert($micro_blog_favourites);
    }
}
